# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
%cd /content/drive/MyDrive/numpy-100
!pip install -r requirements.txt
%run initialise.py

/content/drive/MyDrive/numpy-100


#### 1. Import the numpy package under the name `np` (★☆☆)

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
import numpy as np
print(np.show_config())

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc


#### 3. Create a null vector of size 10 (★☆☆)

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
arr = np.empty((10))
print(arr.nbytes)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
np.arange(10,50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [8]:
np.array([1,2,0,0,4,0]).nonzero()

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [9]:
np.random.random((3,3,3))

array([[[0.17732363, 0.7513172 , 0.10153149],
        [0.95265863, 0.54837427, 0.42682609],
        [0.7523077 , 0.86188769, 0.94648197]],

       [[0.28756612, 0.91290861, 0.36028971],
        [0.90451705, 0.11042852, 0.30343672],
        [0.6033872 , 0.16552006, 0.46190324]],

       [[0.90120084, 0.07220393, 0.94107642],
        [0.6647651 , 0.54306626, 0.78323264],
        [0.61441088, 0.74555276, 0.56070514]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [10]:
np.random.random(30).mean()

np.float64(0.5142501915589083)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [11]:
arr = np.random.random((3,3))
print(np.pad(arr,1,mode='constant',constant_values=0))

[[0.         0.         0.         0.         0.        ]
 [0.         0.30596915 0.82721546 0.8716733  0.        ]
 [0.         0.29111987 0.40832227 0.40738516 0.        ]
 [0.         0.38324329 0.89286062 0.74883016 0.        ]
 [0.         0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [12]:
np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [13]:
np.unravel_index(100,(6,7,8)) # gives coordinate of the 100th element

(np.int64(1), np.int64(5), np.int64(4))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [14]:
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr)) #standartization
print(arr)

[[-1.60364939  0.80058642 -1.27891726 -1.43939293 -1.64386562]
 [ 1.03724989  1.06392068  0.1402178   0.80482742  0.91730402]
 [-1.49438343  0.14370874 -0.70785896  0.33564663  0.87826944]
 [-0.07790731  0.92520589 -1.74217219  0.86919673  0.38081305]
 [ 0.48714902  0.03137881  0.83017204 -0.88660421  1.22910471]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [15]:
m1 = np.random.random((5,3))
m2 = np.random.random((3,2))
np.dot(m1,m2)

array([[0.58868561, 1.21514478],
       [1.35482617, 2.17395771],
       [0.86390026, 1.51348786],
       [1.23256096, 2.15293992],
       [0.72654809, 1.18491105]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

the sum at the start sums 0+1+2+3+4+5+-1 and gives 9
the second one taks numpy.sum and the -1 has no meaning as axis=-1 has no so it gives 10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [16]:
np.array([np.nan]).astype(int).astype(float)


/tmp/ipython-input-3822400139.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

np.array(0) returns a scalar = 0 so the result of first which is float division is not a number as division by 0 is illegal in math, second is int division with floor but it will give 0 as the int division will round down (floor) to 0
The last one converts nan to int than float and gives us its value (seems to be min possible float value)

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [17]:
a1 = np.arange(10)
a2 = np.arange(5,15)
print(np.intersect1d(a1,a2))

[5 6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [19]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipython-input-244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

no as the first will return nan and the second will output a complex number

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [18]:
np.arange('2016-07-01','2016-08-01',dtype=np.datetime64)

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [19]:
arr = np.random.uniform(0,200,10)

print(np.array([int(i) for i in arr])) #running on all array elements and converting to list of ints
print(np.int64(arr)) #passes the array into the int64 object constructor
print(arr.astype(int)) #just changes the type of the array - changes the representation of the cells in memory
print(np.array(arr,dtype=int)) #creates array as ints

[  5 100 145  36  93  44 196  67  91  86]
[  5 100 145  36  93  44 196  67  91  86]
[  5 100 145  36  93  44 196  67  91  86]
[  5 100 145  36  93  44 196  67  91  86]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [20]:
def gen():
  count = 0
  while count <10:
    count+=1
    yield count

np.array([i for  i in gen()])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [21]:
np.random.random(10).sort()

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [22]:
A = np.random.random()
B = np.random.random()
np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [23]:
m1 = np.random.randint(0,1000,(10,2))
print(np.array([(np.hypot(x,y),np.arctan2(y,x)) for (x,y) in m1]))

x,y = m1[:,0], m1[:,1]
print(np.hypot(x,y),np.arctan2(y,x))
X,Y = m1[:,0], m1[:,1]#Better!!!
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[[1.25255738e+03 8.63382385e-01]
 [1.02398828e+03 2.42610122e-01]
 [6.42152630e+02 1.59516377e-01]
 [4.41376257e+02 1.42986050e+00]
 [9.08473995e+02 7.38170666e-02]
 [3.44216502e+02 5.29956504e-01]
 [1.06905800e+03 4.18034378e-01]
 [9.54120013e+02 2.83626415e-01]
 [9.52718741e+02 1.53195033e+00]
 [9.03203742e+02 9.24416572e-01]]
[1252.55738392 1023.98828118  642.15262983  441.37625672  908.47399522
  344.21650164 1069.05799656  954.12001342  952.71874129  903.20374224] [0.86338239 0.24261012 0.15951638 1.4298605  0.07381707 0.5299565
 0.41803438 0.28362642 1.53195033 0.92441657]
[1252.55738392 1023.98828118  642.15262983  441.37625672  908.47399522
  344.21650164 1069.05799656  954.12001342  952.71874129  903.20374224]
[0.86338239 0.24261012 0.15951638 1.4298605  0.07381707 0.5299565
 0.41803438 0.28362642 1.53195033 0.92441657]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [60]:
answer(46)

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)



In [58]:
num_of_points= 10
coor = np.zeros((num_of_points,num_of_points),[('x',float),('y',float)]) #Allocating coordinates sructured array

grid = np.meshgrid(np.linspace(0,1,num_of_points),np.linspace(0,1,num_of_points)) #Splitting the [0,1] range to 10 points of equal distance, than creating a grid between x=0,y=0 to x=1,y=1 of 10*10 points
coor['x'],coor['y'] = grid #filling our structured array with the grid
print(coor)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [67]:
for T in [np.int8, np.int32, np.int64]:
    print(np.iinfo(T).max)
    print(np.iinfo(T).min)
for T in [np.float32, np.float64]:
    print(np.finfo(T).max)
    print(np.finfo(T).min)

127
-128
2147483647
-2147483648
9223372036854775807
-9223372036854775808
3.4028235e+38
-3.4028235e+38
1.7976931348623157e+308
-1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [77]:
vec = np.random.randint(1,100,size=np.random.randint(100))
scalar = np.random.randint(100)
print(vec,scalar)
vec[np.argmin(np.abs(vec-scalar))] #smallest distance from scalar is closest in value

[49 62 39 60 74] 69


np.int64(74)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [93]:
coor = np.random.random((10,2))
X,Y = np.atleast_2d(coor[:,0],coor[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

(10, 2)
[[0.         0.83700091 0.84726503 0.6765231  0.76124266 0.12384434
  0.55339499 0.20572983 0.67297987 0.71759875]
 [0.83700091 0.         0.39198084 1.05088485 0.08185284 0.9438653
  0.77085537 0.9017294  0.43612974 0.84028677]
 [0.84726503 0.39198084 0.         1.28261196 0.35390885 0.91662625
  1.01568424 0.98894815 0.18338067 1.12752035]
 [0.6765231  1.05088485 1.28261196 0.         1.01396915 0.754668
  0.28002967 0.48010818 1.1598212  0.27335542]
 [0.76124266 0.08185284 0.35390885 1.01396915 0.         0.86597841
  0.73488093 0.83518606 0.36925589 0.81845624]
 [0.12384434 0.9438653  0.91662625 0.754668   0.86597841 0.
  0.66251882 0.27504468 0.73632194 0.82476515]
 [0.55339499 0.77085537 1.01568424 0.28002967 0.73488093 0.66251882
  0.         0.41190208 0.90626465 0.16487893]
 [0.20572983 0.9017294  0.98894815 0.48010818 0.83518606 0.27504468
  0.41190208 0.         0.82708958 0.56659037]
 [0.67297987 0.43612974 0.18338067 1.1598212  0.36925589 0.73632194
  0.90626465 0.

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [100]:
from io import StringIO
s= StringIO('''1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

''')
print(np.genfromtxt(s, delimiter=',', filling_values=0))

[[ 1.  2.  3.  4.  5.]
 [ 6.  0.  0.  7.  8.]
 [ 0.  0.  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [104]:
sigma, mu = 1.0, 0.0
x,y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10)) #creating x,y grid for the function points
#Simple calc of gaussian function
dist = np.sqrt(x**2+y**2)
coeff = 1/(sigma*np.sqrt(2*np.pi))
exp = np.exp(-(dist-mu)**2/(2*((sigma)**2)))
g = coeff*exp
print(g)

[[0.14676266 0.17881426 0.20736816 0.2288945  0.24048168 0.24048168
  0.2288945  0.20736816 0.17881426 0.14676266]
 [0.17881426 0.21786563 0.25265543 0.27888292 0.29300063 0.29300063
  0.27888292 0.25265543 0.21786563 0.17881426]
 [0.20736816 0.25265543 0.29300063 0.32341625 0.33978835 0.33978835
  0.32341625 0.29300063 0.25265543 0.20736816]
 [0.2288945  0.27888292 0.32341625 0.35698924 0.37506088 0.37506088
  0.35698924 0.32341625 0.27888292 0.2288945 ]
 [0.24048168 0.29300063 0.33978835 0.37506088 0.39404734 0.39404734
  0.37506088 0.33978835 0.29300063 0.24048168]
 [0.24048168 0.29300063 0.33978835 0.37506088 0.39404734 0.39404734
  0.37506088 0.33978835 0.29300063 0.24048168]
 [0.2288945  0.27888292 0.32341625 0.35698924 0.37506088 0.37506088
  0.35698924 0.32341625 0.27888292 0.2288945 ]
 [0.20736816 0.25265543 0.29300063 0.32341625 0.33978835 0.33978835
  0.32341625 0.29300063 0.25265543 0.20736816]
 [0.17881426 0.21786563 0.25265543 0.27888292 0.29300063 0.29300063
  0.27888292

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [119]:
n = np.random.randint(1,15)
mat = np.random.random((n,2))
print(mat-mat.mean(axis=1,keepdims=True))


[[ 0.40110095 -0.40110095]
 [-0.38089671  0.38089671]
 [ 0.06380223 -0.06380223]
 [ 0.1131874  -0.1131874 ]]


#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [123]:
arr = np.random.random((np.random.randint(1,20),np.random.randint(1,20)))
arr.any(axis=0).any() #first any goes through all cols, second any looks for false meaning there is one col that has null

# Author: Warren Weckesser

# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))


#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [143]:
a1 = np.random.random((1,3))
a2 = np.random.random((3,1))
res = np.zeros((3,3))
#nditer goes over each individual element - element-wise
for x,y,r in np.nditer([a1,a2,res],op_flags=[['readonly'],['readonly'],['writeonly']]):
  r[...] = x+y # [...] is a holder for unknown number of elements and conent in the r elemnt in place [a,b] in the matrix
  # It doesnt assign to the r var but the in place memory that r points to
print(res)

[[1.05256533 0.81711814 0.36689476]
 [0.94301301 0.70756582 0.25734244]
 [1.03775002 0.80230283 0.35207945]]


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)