# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd /content/drive/MyDrive/numpy-100
!pip install -r requirements.txt
%run initialise.py
from time import time

/content/drive/MyDrive/numpy-100


#### 1. Import the numpy package under the name `np` (★☆☆)

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
import numpy as np
print(np.show_config())

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc


#### 3. Create a null vector of size 10 (★☆☆)

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
arr = np.empty((10))
print(arr.nbytes)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [6]:
np.arange(10,50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [7]:
np.array([1,2,0,0,4,0]).nonzero()

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [8]:
np.random.random((3,3,3))

array([[[0.68761664, 0.85415872, 0.1474521 ],
        [0.82655928, 0.64560611, 0.60210749],
        [0.9169583 , 0.75413735, 0.77741037]],

       [[0.17049188, 0.94864953, 0.63812686],
        [0.22472969, 0.12448054, 0.81579625],
        [0.17657343, 0.34648222, 0.70898506]],

       [[0.82678448, 0.2751913 , 0.30789005],
        [0.69277902, 0.81415897, 0.2223031 ],
        [0.09662881, 0.7152155 , 0.15710456]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [9]:
np.random.random(30).mean()

np.float64(0.49048466171363925)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [10]:
arr = np.random.random((3,3))
print(np.pad(arr,1,mode='constant',constant_values=0))

[[0.         0.         0.         0.         0.        ]
 [0.         0.62684198 0.30982914 0.77950332 0.        ]
 [0.         0.27669433 0.55679793 0.66567211 0.        ]
 [0.         0.42605473 0.6085433  0.17003292 0.        ]
 [0.         0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [11]:
np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [12]:
np.unravel_index(100,(6,7,8)) # gives coordinate of the 100th element

(np.int64(1), np.int64(5), np.int64(4))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [13]:
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr)) #standartization
print(arr)

[[ 1.19265952 -1.18642205 -0.17188981  1.35828871  0.64206069]
 [ 1.69450416 -0.87380625  0.73622289 -0.87485275 -0.03677282]
 [-0.59072261 -0.29026726  1.14728896 -0.14328913 -1.42722778]
 [ 0.73694968  0.35358054 -1.51223442 -1.55480975 -1.11369739]
 [ 1.61008013 -0.64362552 -0.2382854   1.20668242 -0.02041477]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [14]:
m1 = np.random.random((5,3))
m2 = np.random.random((3,2))
np.dot(m1,m2)

array([[0.96179289, 0.575914  ],
       [0.50720122, 0.32717163],
       [0.91288831, 0.60842235],
       [0.84851601, 0.52161458],
       [0.69481187, 0.4700162 ]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

the sum at the start sums 0+1+2+3+4+5+-1 and gives 9
the second one taks numpy.sum and the -1 has no meaning as axis=-1 has no so it gives 10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [15]:
np.array([np.nan]).astype(int).astype(float)


/tmp/ipython-input-3822400139.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

np.array(0) returns a scalar = 0 so the result of first which is float division is not a number as division by 0 is illegal in math, second is int division with floor but it will give 0 as the int division will round down (floor) to 0
The last one converts nan to int than float and gives us its value (seems to be min possible float value)

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [16]:
a1 = np.arange(10)
a2 = np.arange(5,15)
print(np.intersect1d(a1,a2))

[5 6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

no as the first will return nan and the second will output a complex number

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [17]:
np.arange('2016-07-01','2016-08-01',dtype=np.datetime64)

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [18]:
arr = np.random.uniform(0,200,10)

print(np.array([int(i) for i in arr])) #running on all array elements and converting to list of ints
print(np.int64(arr)) #passes the array into the int64 object constructor
print(arr.astype(int)) #just changes the type of the array - changes the representation of the cells in memory
print(np.array(arr,dtype=int)) #creates array as ints

[179  99  70 183  93  60  53 192  40 185]
[179  99  70 183  93  60  53 192  40 185]
[179  99  70 183  93  60  53 192  40 185]
[179  99  70 183  93  60  53 192  40 185]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [19]:
def gen():
  count = 0
  while count <10:
    count+=1
    yield count

np.array([i for  i in gen()])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [20]:
np.random.random(10).sort()

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [21]:
A = np.random.random()
B = np.random.random()
np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [22]:
m1 = np.random.randint(0,1000,(10,2))
print(np.array([(np.hypot(x,y),np.arctan2(y,x)) for (x,y) in m1]))

x,y = m1[:,0], m1[:,1]
print(np.hypot(x,y),np.arctan2(y,x))
X,Y = m1[:,0], m1[:,1]#Better!!!
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[[7.08045902e+02 3.15944456e-01]
 [7.28829884e+02 1.04943783e+00]
 [5.92095431e+02 6.08385332e-02]
 [7.88112302e+02 7.05460855e-01]
 [3.88911301e+02 7.89034511e-01]
 [5.76944538e+02 4.52020226e-01]
 [7.56788610e+02 1.41824746e+00]
 [6.43257336e+02 1.33863747e+00]
 [9.10249416e+02 9.58720350e-01]
 [8.21301406e+02 1.31223315e+00]]
[708.04590247 728.82988413 592.0954315  788.11230164 388.91130094
 576.94453806 756.78860985 643.25733575 910.24941637 821.30140631] [0.31594446 1.04943783 0.06083853 0.70546085 0.78903451 0.45202023
 1.41824746 1.33863747 0.95872035 1.31223315]
[708.04590247 728.82988413 592.0954315  788.11230164 388.91130094
 576.94453806 756.78860985 643.25733575 910.24941637 821.30140631]
[0.31594446 1.04943783 0.06083853 0.70546085 0.78903451 0.45202023
 1.41824746 1.33863747 0.95872035 1.31223315]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)



In [23]:
num_of_points= 10
coor = np.zeros((num_of_points,num_of_points),[('x',float),('y',float)]) #Allocating coordinates sructured array

grid = np.meshgrid(np.linspace(0,1,num_of_points),np.linspace(0,1,num_of_points)) #Splitting the [0,1] range to 10 points of equal distance, than creating a grid between x=0,y=0 to x=1,y=1 of 10*10 points
coor['x'],coor['y'] = grid #filling our structured array with the grid
print(coor)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [24]:
for T in [np.int8, np.int32, np.int64]:
    print(np.iinfo(T).max)
    print(np.iinfo(T).min)
for T in [np.float32, np.float64]:
    print(np.finfo(T).max)
    print(np.finfo(T).min)

127
-128
2147483647
-2147483648
9223372036854775807
-9223372036854775808
3.4028235e+38
-3.4028235e+38
1.7976931348623157e+308
-1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [25]:
vec = np.random.randint(1,100,size=np.random.randint(100))
scalar = np.random.randint(100)
print(vec,scalar)
vec[np.argmin(np.abs(vec-scalar))] #smallest distance from scalar is closest in value

[23 13 26 21 57 98 67 52 24 98 30 64 71 73 40 78 82 46 66 57 70 50 42 85
 83 32 68 51 22 14  9 87 18 86 82 33  4 15 54 39 86 42 18 35 58 12] 16


np.int64(15)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [26]:
coor = np.random.random((10,2))
X,Y = np.atleast_2d(coor[:,0],coor[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         1.01826881 0.92401896 0.4481608  0.83084394 0.42858347
  0.3004657  0.55301488 1.00843919 0.5549551 ]
 [1.01826881 0.         0.31349225 0.57139392 0.34684696 0.79131135
  1.05923253 0.7563142  0.3880974  0.51554074]
 [0.92401896 0.31349225 0.         0.50274669 0.09352101 0.83689569
  0.87778798 0.5162783  0.1116884  0.5674439 ]
 [0.4481608  0.57139392 0.50274669 0.         0.41454165 0.37323087
  0.52305387 0.38410086 0.60187289 0.2074953 ]
 [0.83084394 0.34684696 0.09352101 0.41454165 0.         0.75947424
  0.78750356 0.43477172 0.18776341 0.49804849]
 [0.42858347 0.79131135 0.83689569 0.37323087 0.75947424 0.
  0.67902533 0.72231475 0.94498866 0.28069814]
 [0.3004657  1.05923253 0.87778798 0.52305387 0.78750356 0.67902533
  0.         0.38969152 0.93528586 0.70336545]
 [0.55301488 0.7563142  0.5162783  0.38410086 0.43477172 0.72231475
  0.38969152 0.         0.55662938 0.5881058 ]
 [1.00843919 0.3880974  0.1116884  0.60187289 0.18776341 0.94498866
  0.93528586 0.55662

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [27]:
from io import StringIO
s= StringIO('''1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

''')
print(np.genfromtxt(s, delimiter=',', filling_values=0))

[[ 1.  2.  3.  4.  5.]
 [ 6.  0.  0.  7.  8.]
 [ 0.  0.  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [28]:
sigma, mu = 1.0, 0.0
x,y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10)) #creating x,y grid for the function points
#Simple calc of gaussian function
dist = np.sqrt(x**2+y**2)
coeff = 1/(sigma*np.sqrt(2*np.pi))
exp = np.exp(-(dist-mu)**2/(2*((sigma)**2)))
g = coeff*exp
print(g)

[[0.14676266 0.17881426 0.20736816 0.2288945  0.24048168 0.24048168
  0.2288945  0.20736816 0.17881426 0.14676266]
 [0.17881426 0.21786563 0.25265543 0.27888292 0.29300063 0.29300063
  0.27888292 0.25265543 0.21786563 0.17881426]
 [0.20736816 0.25265543 0.29300063 0.32341625 0.33978835 0.33978835
  0.32341625 0.29300063 0.25265543 0.20736816]
 [0.2288945  0.27888292 0.32341625 0.35698924 0.37506088 0.37506088
  0.35698924 0.32341625 0.27888292 0.2288945 ]
 [0.24048168 0.29300063 0.33978835 0.37506088 0.39404734 0.39404734
  0.37506088 0.33978835 0.29300063 0.24048168]
 [0.24048168 0.29300063 0.33978835 0.37506088 0.39404734 0.39404734
  0.37506088 0.33978835 0.29300063 0.24048168]
 [0.2288945  0.27888292 0.32341625 0.35698924 0.37506088 0.37506088
  0.35698924 0.32341625 0.27888292 0.2288945 ]
 [0.20736816 0.25265543 0.29300063 0.32341625 0.33978835 0.33978835
  0.32341625 0.29300063 0.25265543 0.20736816]
 [0.17881426 0.21786563 0.25265543 0.27888292 0.29300063 0.29300063
  0.27888292

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [29]:
n = np.random.randint(1,15)
mat = np.random.random((n,2))
print(mat-mat.mean(axis=1,keepdims=True))


[[ 0.13605181 -0.13605181]
 [-0.15894922  0.15894922]
 [-0.11263455  0.11263455]]


#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [30]:
arr = np.random.random((np.random.randint(1,20),np.random.randint(1,20)))
arr.any(axis=0).any() #first any goes through all cols, second any looks for false meaning there is one col that has null

np.True_

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [31]:
a1 = np.random.random((1,3))
a2 = np.random.random((3,1))
res = np.zeros((3,3))
#nditer goes over each individual element - element-wise
for x,y,r in np.nditer([a1,a2,res],op_flags=[['readonly'],['readonly'],['writeonly']]):
  r[...] = x+y # [...] is a holder for unknown number of elements and conent in the r elemnt in place [a,b] in the matrix
  # It doesnt assign to the r var but the in place memory that r points to
print(res)

[[0.84348101 1.11333659 0.74056311]
 [0.89293859 1.16279417 0.79002069]
 [0.68024326 0.95009884 0.57732536]]


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [32]:
ind = np.random.randint(0,10,10)
vec = np.zeros(10)
print(vec,ind)
np.add.at(vec,ind,1)
print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [9 6 0 1 8 8 3 9 8 2]
[1. 1. 1. 1. 0. 0. 1. 0. 3. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [33]:
w,h = 256,256
img = np.random.randint(0,5,(h,w,3)).astype(np.ubyte)
pixels = img.reshape(-1,3) # will turn image (Arr of (x,y,[R,G,B]) to array of ([R,G,B] in which each row represent a pixel - pixel (x,y) will go to row Index} = (x*Width}) + y))
print(len(np.unique(pixels,axis=0)))

125


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [65]:
D = np.random.randint(0,10,100)
S = np.random.randint(0,10,100)
D_sum = np.bincount(S, weights=D) #For each index in S: take D[index] and add it to the sum (If we didnt use weights we would just get 1 instead of D[index] which will just give us the count of indexs in S)
D_count = np.bincount(S)
print(D_sum/D_count)

[3.75       5.85714286 5.38461538 3.81818182 4.4        3.7
 7.4        5.91666667 4.72727273 5.44444444]


#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [49]:
vec = np.array([1,2,3,4,5])
zer = np.zeros(len(vec)+3*(len(vec)-1)) # len should be len of vec (to have original elemetns) + 3 zeroes between each 2 elements (num of spaces in between is alway len -1)
print(len(zer))
zer[::4]=vec
print(zer)

17
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [62]:
arr = np.random.random((5,5))
arr[[0,1]]=arr[[1,0]]
print(arr)

[[0.71244577 0.74461134 0.83122821 0.88216048 0.45998468]
 [0.39170161 0.85913179 0.21419189 0.96776399 0.61902253]
 [0.29726694 0.58227961 0.30090002 0.85655653 0.22446451]
 [0.9671925  0.84383461 0.50051797 0.32838765 0.55998706]
 [0.54638586 0.77313125 0.9458448  0.09791487 0.56291421]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [71]:
C = np.random.randint(0,10,10)
vals = np.arange(len(C)) #C contains how much to repeat for each element. in C[i] is the num of appereances of value i in A, so indexs of C are the values of A, C[i] is the number of their appearences
A = np.repeat(vals,C)
print(C,A)

[2 4 1 3 9 5 8 5 1 1] [0 0 1 1 1 1 2 3 3 3 4 4 4 4 4 4 4 4 4 5 5 5 5 5 6 6 6 6 6 6 6 6 7 7 7 7 7
 8 9]


#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [75]:
Z = np.random.randint(0,10,10)
print(Z)
print(np.lib.stride_tricks.sliding_window_view(Z,3))

[8 7 5 8 6 6 1 5 6 9]
[[8 7 5]
 [7 5 8]
 [5 8 6]
 [8 6 6]
 [6 6 1]
 [6 1 5]
 [1 5 6]
 [5 6 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [87]:
P0=np.random.random((10,2))
P1=np.random.random((10,2))
p=np.random.random((1,2))
lines = P1 - P0
height = P0 - p
area = np.abs(lines[:, 0] * height[:,1] - lines[:, 1] * height[:,0]) #Calculating the area created by the cross product of the 2 lines
base_length = np.sqrt((lines**2).sum(axis=1))
print(area/base_length)
#Distance between p and the line is the height of the triangle. So we calculate the area of the triangle, than find the height from h*b = area

[0.78794888 0.30958575 0.00476852 0.24607244 0.24405752 0.48352537
 0.09700896 0.76408772 0.11598173 0.1545304 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

In [98]:
mat = np.random.random((5,5))
print(np.linalg.matrix_rank(mat))

5


#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [106]:
mat = np.random.rand(10,10)
print(np.lib.stride_tricks.sliding_window_view(mat, (3, 3)))

[[[[0.17668531 0.56535591 0.08649553]
   [0.06362388 0.26872724 0.46786419]
   [0.65518555 0.3969465  0.30951425]]

  [[0.56535591 0.08649553 0.32499382]
   [0.26872724 0.46786419 0.03358186]
   [0.3969465  0.30951425 0.97160733]]

  [[0.08649553 0.32499382 0.53250077]
   [0.46786419 0.03358186 0.75502744]
   [0.30951425 0.97160733 0.41557108]]

  [[0.32499382 0.53250077 0.03165502]
   [0.03358186 0.75502744 0.1708479 ]
   [0.97160733 0.41557108 0.10382465]]

  [[0.53250077 0.03165502 0.29085027]
   [0.75502744 0.1708479  0.27009822]
   [0.41557108 0.10382465 0.15053901]]

  [[0.03165502 0.29085027 0.63031065]
   [0.1708479  0.27009822 0.27741684]
   [0.10382465 0.15053901 0.38811706]]

  [[0.29085027 0.63031065 0.54303171]
   [0.27009822 0.27741684 0.0336152 ]
   [0.15053901 0.38811706 0.8308996 ]]

  [[0.63031065 0.54303171 0.8170033 ]
   [0.27741684 0.0336152  0.61373013]
   [0.38811706 0.8308996  0.15978142]]]


 [[[0.06362388 0.26872724 0.46786419]
   [0.65518555 0.3969465  0.3095

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [120]:
p, n = np.random.randint(2,20,2)
mat = np.ones((p,n,n))
vec = np.ones((p,n,1))
print(n, np.einsum('pij,pjk->ik', mat, vec).shape)
#multiplying p pairs of (n x n) and (n x 1) shapes, the j index handles the matrix multiplication, and the p index handles the final summation of those p results.

7 (7, 1)


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

*   List item
*   List item



In [122]:
neigh = (cells[0:-2, 0:-2] + cells[0:-2, 1:-1] + cells[0:-2, 2:] +
      cells[1:-1, 0:-2]                + cells[1:-1, 2:] +
      cells[2:  , 0:-2] + cells[2:  , 1:-1] + cells[2:  , 2:])
dead = (neigh == 3) & (cells[1:-1, 1:-1] == 0)
alive = ((neigh == 2) | (neigh == 3)) & (cells[1:-1, 1:-1] == 1)

No hints provided...


#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

> Add blockquote



In [136]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5])
v3 = np.array([6, 7])
vecs = [v1,v2,v3]
grid = np.meshgrid(*vecs, indexing='ij') # Inflating the matrixes for the "every item"
np.stack(grid, axis=-1).reshape(-1, len(vecs)) # Stack combines them together for the cartesian of all posible combination
a = np.arange(4) # [0, 1, 2, 3]
b = np.arange(4, 8) # [4, 5, 6, 7]

stacked = np.stack([a, b], axis=0)
print(stacked,stacked.shape)

stacked_depth = np.stack([a, b], axis=-1)
print(stacked, stacked_depth.shape)

[[0 1 2 3]
 [4 5 6 7]] (2, 4)
[[0 1 2 3]
 [4 5 6 7]] (4, 2)


#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using

*   List item
*   List item

3 different methods (★★★)

In [139]:
np.pow(x,3)
x**3
x*x*x
np.einsum('i,i,i->i',x,x,x)

ValueError: einstein sum subscripts string contains too many subscripts for operand 0

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [146]:
arr = np.random.randint(0,20,(10,3))
print(arr[np.ptp(arr, axis=1) > 0])

[[18  7  6]
 [ 3  4  4]
 [17 17  8]
 [19 19 14]
 [ 5  3  9]
 [ 4  9 14]
 [ 3 12  3]
 [12 11  7]
 [15  3 17]
 [10 16 19]]
[[18  7  6]
 [ 3  4  4]
 [17 17  8]
 [19 19 14]
 [ 5  3  9]
 [ 4  9 14]
 [ 3 12  3]
 [12 11  7]
 [15  3 17]
 [10 16 19]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
np.unique(arr,axis=0)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [149]:
t=np.linspace(0, 1, 10)**2
x=t
y=t**2

dx = np.diff(x)
dy = np.diff(y)
distances = np.sqrt(dx**2 + dy**2)

accumulated_dist = np.concatenate(([0], np.cumsum(distances)))

num_samples = 50
equidistant_dist = np.linspace(0, accumulated_dist[-1], num_samples)

x_new = np.interp(equidistant_dist, accumulated_dist, x)
y_new = np.interp(equidistant_dist, accumulated_dist, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [151]:
arr = np.random.randn(100)
n = 1000
idx = np.random.randint(0, arr.size, (n, arr.size))
means = arr[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])